/**
 * Config Generator for CLIProxyAPI
 *
 * Generates config.yaml for CLIProxyAPI based on provider.
 * Handles OAuth token paths and provider-specific settings.
 */

import * as fs from 'fs';
import * as path from 'path';
import { getCcsDir } from '../utils/config-manager';
import { CLIProxyProvider, ProviderConfig, ProviderModelMapping } from './types';

/** Default CLIProxy port */
export const CLIPROXY_DEFAULT_PORT = 8317;

/** Internal API key for CCS-managed requests */
const CCS_INTERNAL_API_KEY = 'ccs-internal-managed';

/**
 * Provider configurations with model mappings
 */
export const PROVIDER_CONFIGS: Record<CLIProxyProvider, ProviderConfig> = {
  gemini: {
    name: 'gemini',
    displayName: 'Gemini',
    models: {
      defaultModel: 'gemini-2.0-flash',
      claudeModel: 'gemini-2.0-flash',
      opusModel: 'gemini-2.0-flash-thinking-exp',
      sonnetModel: 'gemini-2.0-flash',
      haikuModel: 'gemini-2.0-flash-lite',
    },
    requiresOAuth: true,
  },
  chatgpt: {
    name: 'chatgpt',
    displayName: 'ChatGPT',
    models: {
      defaultModel: 'gpt-4o',
      claudeModel: 'gpt-4o',
      opusModel: 'o1',
      sonnetModel: 'gpt-4o',
      haikuModel: 'gpt-4o-mini',
    },
    requiresOAuth: true,
  },
  qwen: {
    name: 'qwen',
    displayName: 'Qwen',
    models: {
      defaultModel: 'qwen-max',
      claudeModel: 'qwen-max',
      opusModel: 'qwen-max',
      sonnetModel: 'qwen-plus',
      haikuModel: 'qwen-turbo',
    },
    requiresOAuth: true,
  },
};

/**
 * Get provider configuration
 */
export function getProviderConfig(provider: CLIProxyProvider): ProviderConfig {
  const config = PROVIDER_CONFIGS[provider];
  if (!config) {
    throw new Error(`Unknown provider: ${provider}`);
  }
  return config;
}

/**
 * Get model mapping for provider
 */
export function getModelMapping(provider: CLIProxyProvider): ProviderModelMapping {
  return getProviderConfig(provider).models;
}

/**
 * Get auth directory for CLIProxyAPI
 */
export function getAuthDir(): string {
  return path.join(getCcsDir(), 'cliproxy-auth');
}

/**
 * Get config file path
 */
export function getConfigPath(): string {
  return path.join(getCcsDir(), 'cliproxy.config.yaml');
}

/**
 * Generate config.yaml content for provider
 */
function generateConfigContent(
  provider: CLIProxyProvider,
  port: number = CLIPROXY_DEFAULT_PORT
): string {
  const authDir = getAuthDir();

  // Base config (always present)
  let config = `# CLIProxyAPI config generated by CCS
# Provider: ${provider}
# Generated: ${new Date().toISOString()}

port: ${port}
debug: false
logging-to-file: false
usage-statistics-enabled: false

# CCS internal authentication
api-keys:
  - "${CCS_INTERNAL_API_KEY}"

# OAuth tokens stored here
auth-dir: "${authDir}"
`;

  // Provider-specific config
  switch (provider) {
    case 'gemini':
      config += `
# Gemini configuration (OAuth-managed)
# API keys will be loaded from auth-dir after OAuth
gemini-api-key: []
`;
      break;

    case 'chatgpt':
      config += `
# ChatGPT/Codex configuration (OAuth-managed)
# API keys will be loaded from auth-dir after OAuth
codex-api-key: []
`;
      break;

    case 'qwen':
      config += `
# Qwen configuration (API key required)
openai-compatibility:
  - name: "qwen"
    base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api-key-entries: []
`;
      break;
  }

  return config;
}

/**
 * Generate config.yaml file for provider
 * @returns Path to generated config file
 */
export function generateConfig(
  provider: CLIProxyProvider,
  port: number = CLIPROXY_DEFAULT_PORT
): string {
  const configPath = getConfigPath();
  const configContent = generateConfigContent(provider, port);

  // Ensure directories exist
  const authDir = getAuthDir();
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.mkdirSync(authDir, { recursive: true });

  // Write config with secure permissions (0600)
  fs.writeFileSync(configPath, configContent, { mode: 0o600 });

  return configPath;
}

/**
 * Check if config exists for provider
 */
export function configExists(): boolean {
  return fs.existsSync(getConfigPath());
}

/**
 * Delete config file
 */
export function deleteConfig(): void {
  const configPath = getConfigPath();
  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
  }
}

/**
 * Get environment variables for Claude CLI
 */
export function getClaudeEnvVars(
  provider: CLIProxyProvider,
  port: number = CLIPROXY_DEFAULT_PORT
): NodeJS.ProcessEnv {
  const models = getModelMapping(provider);

  return {
    ANTHROPIC_BASE_URL: `http://127.0.0.1:${port}`,
    ANTHROPIC_AUTH_TOKEN: CCS_INTERNAL_API_KEY,
    ANTHROPIC_MODEL: models.claudeModel,
    ANTHROPIC_DEFAULT_OPUS_MODEL: models.opusModel || models.claudeModel,
    ANTHROPIC_DEFAULT_SONNET_MODEL: models.sonnetModel || models.claudeModel,
    ANTHROPIC_DEFAULT_HAIKU_MODEL: models.haikuModel || models.claudeModel,
  };
}
